### ISSUE TITLE
[Hotkey] - Cheatsheet with all the key mappings.

### ISSUE THREAD

**Issue by prubiella** [stream-pi/essentialactions#14]
*Issue Description: *
It would be nice to have a cheatsheet with all the key mapping names in order to make it more easy to the new users to create their Hotkey buttons. 

I'm thinking in something like: 

KEY | MAPPING IN PLUGIN | MAPPING TO HOST
--- | --------------------- | ------------------
Ctrl | CONTROL | CONTROL
Alt | ALT | ALT
Win | WINDOWS/SUPER/COMMAND | WINDOWS
\ | BACK_SLASH | BACK_SLASH

**Comment by rnayabed** [comment]
This has been now done
