### ISSUE TITLE
[Hotkey] - Replace BACK_SLASH per PIPE

### ISSUE THREAD

**Issue by prubiella** [stream-pi/essentialactions#15]
Hi, I think this is wrong and should be `PIPE` instead of `BACK_SLASH`

https://github.com/stream-pi/essentialactions/blob/84c7a3034b00c852a00f6f890d7158de64c8a5b7/hotkeyaction/src/main/java/com/stream_pi/hotkeyaction/HotkeyAction.java#L151

**Comment by rnayabed** [comment]
There is no `PIPE` in java. Any occurrence of `|` is changed to `SHIFT,\` 

https://github.com/stream-pi/essentialactions/blob/211e6fb4d91f2d754dd7e3985ef2babd998b5560/hotkeyaction/src/main/java/com/stream_pi/hotkeyaction/HotkeyAction.java#L60
