### ISSUE TITLE
Update plugins to use latest version of action-api

### ISSUE THREAD

**Issue by j4ckofalltrades** [stream-pi/essentialactions#24]
Update plugins to use the latest [Action API](https://github.com/stream-pi/actionapi) version (contains backwards-incompatible changes).

- [x] Hotkey
- [x] Media File
- [x] Media Key
- [x] OBS Actions
- [x] Play Audio Clip
- [x] Run Command
- [x] Text Block
- [x] Twitch
- [x] Twitter

**Comment by EVNPC** [comment]
the Play Audio Clip Action also needs updating

**Comment by rnayabed** [comment]
Done
